// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TutoringQuiz.Infrastructure.Persistence;

#nullable disable

namespace TutoringQuiz.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924093253_ScoresNeverBelowZero")]
    partial class ScoresNeverBelowZero
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.20");

            modelBuilder.Entity("TutoringQuiz.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AnsweredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SelectedOptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedOptionId");

                    b.HasIndex("AttemptId", "QuestionId")
                        .IsUnique();

                    b.ToTable("AttemptAnswers", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Attempts.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeadlineUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxScore")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Score")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnansweredCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WrongCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("QuizId", "StudentId")
                        .IsUnique();

                    b.ToTable("QuizAttempts", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.ClassRooms.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Grade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ClassRooms", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Order");

                    b.ToTable("Options", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QuizId", "Order");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ClosesAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpensAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("WrongAnswerPenaltyPercent")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.QuizClassRoom", b =>
                {
                    b.Property<Guid>("QuizId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassRoomId")
                        .HasColumnType("TEXT");

                    b.HasKey("QuizId", "ClassRoomId");

                    b.HasIndex("ClassRoomId");

                    b.ToTable("QuizClassRooms", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassRoomId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameNormalized")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("UsernameNormalized")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Attempts.AttemptAnswer", b =>
                {
                    b.HasOne("TutoringQuiz.Domain.Attempts.QuizAttempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TutoringQuiz.Domain.Quizzes.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringQuiz.Domain.Quizzes.Option", null)
                        .WithMany()
                        .HasForeignKey("SelectedOptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Attempts.QuizAttempt", b =>
                {
                    b.HasOne("TutoringQuiz.Domain.Quizzes.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringQuiz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Option", b =>
                {
                    b.HasOne("TutoringQuiz.Domain.Quizzes.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Question", b =>
                {
                    b.HasOne("TutoringQuiz.Domain.Quizzes.Quiz", null)
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Quiz", b =>
                {
                    b.HasOne("TutoringQuiz.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.QuizClassRoom", b =>
                {
                    b.HasOne("TutoringQuiz.Domain.ClassRooms.ClassRoom", null)
                        .WithMany()
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TutoringQuiz.Domain.Quizzes.Quiz", null)
                        .WithMany("ClassRooms")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Users.User", b =>
                {
                    b.HasOne("TutoringQuiz.Domain.ClassRooms.ClassRoom", null)
                        .WithMany()
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Attempts.QuizAttempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("TutoringQuiz.Domain.Quizzes.Quiz", b =>
                {
                    b.Navigation("ClassRooms");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
